<?php $this->titre = "Manifeste"; ?>
<button id="sommaire" title="Sommaire"><i class="fas fa-chevron-right"></i></button>
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" id="fermerSommaire">&times;</a>
    <a href="#Introduction">Introduction</a>
    <a href="#Sécurité">Sécurité & Immigration</a>
    <a href="#Education">Education</a>
    <a href="#Ecologie">Ecologie</a>
    <a href="#Relations">Relations internationales</a>
    <a href="#Défense">Défense</a>
    <a href="#Finance">Finance</a>
    <a href="#Agriculture">Agriculture</a>
    <a href="#Conclusion">Conclusion</a>
</div>
<!-- Contenu de la div Center -->
<div class="container-pages">
    <div class="manif-chapters" id="Introduction">
        <h1 class="center" >Introduction</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">
        “Une société sans religion est un vaisseau sans boussole” disait Napoléon. Loin de nous l’idée d’instaurer le catholicisme pour tous ou toute autre religion. Mais force est de constater que le grand vide de notre époque est spirituel. Le relativisme domine toute notre société, et par elle nos pensées. Et quand le relativisme gouverne, les structures s’effondrent. Culturelles, sociales, morales. Aucune ne tient face à la tempête moderniste. Ce dont a besoin la France c’est d’idéal et de structures. L’un ne peut exister sans l’autre. Lorsque l’idéal est seul, il est utopique, irréalisable et se heurte aux réalités qui, alors qu’elles devraient l'abîmer, semblent balayables ou insignifiantes à ses partisans. Lorsque les structures sont seules, personne ne perçoit leur utilité. Existante certes, mais trop rationnelle pour qui n’a pas l'œil averti. Accompagné de l’idéal, les structures sont soutenues. Et avec les structures, l’idéal est possible. Pour l’idéal, nous l’avons devant nous: la France. Retrouver sa grandeur passée, sa capacité à illuminer l’Europe et le Monde ou comme disait Ernest Renan “Dans le passé, un héritage de gloire et de regrets à partager, dans l'avenir un même programme à réaliser”. Quant aux structures, il s’agit du sujet de ce Manifeste.
        Patriotisme, Souverainisme, Méritocratie. Telle est notre devise.


        Patriotisme tout d’abord. La patrie est la terre des pères. Et par nos pères, la terre de nos ancêtres. C’est cette notion qui est la plus importante. Nous œuvrons dans la continuité des générations passées. Nous sommes l’héritage de leurs volontés, de leurs réussites comme de leurs échecs. Le Patriotisme, c’est l’amour de cet héritage. L’amour de tout ce qui constitue la France, et de tout ce qui nous constitue en tant que français. Aucune vision politique saine ne peut s’écrire sans cette condition préalable. Aimer est la seule source de motivation sincère et digne de confiance. Et tous les acteurs politiques devraient se revendiquer du patriotisme. Sinon ils n’agissent pas pour le bien commun. Ils œuvrent soit pour le compte de l’étranger, soit pour leur propre compte ou celui de leur communauté. En clair: ni pour la Patrie, ni pour la Nation. Ceux qui obligent les patriotes à se revendiquer d’un bord politique particulier, celui qu’on appelle traditionnellement la Droite, sont les victimes de notre époque déracinante. Ils doivent être éduqués ou combattus. Mais ce sont des ennemis tout désignés de la cause française.

        Souverainisme ensuite. La souveraineté est la liberté de décision. La liberté de la France à décider pour elle-même. Qui oserait supprimer ce droit à un adulte ? Personne, alors pourquoi infantiliser la France ? Ce pays est l’un des plus vieux du monde. La France a su s’auto-déterminer pendant des siècles, dans les époques de lumière où florissaient l’ingéniosité, la culture et l’art comme dans les périodes les plus sombres. La souveraineté ne veut en aucun cas dire le repli comme les détracteurs cosmopolites aiment à le faire croire. La diplomatie et le commerce ont créé les instances internationales et non l’inversion absurde qu’on entend parfois. Se retirer d’une instance ne veut pas dire rompre les contacts politiques ou économiques avec qui que ce soit. Le rétablissement de la souveraineté n’est que le rétablissement de la liberté de choix. Et pour appliquer toute politique sérieuse, il faut être libre. Sans ça, la gouvernance nationale est incapable de faire ce qui est bon pour son peuple.

        Méritocratie enfin. A ce mot, plus qu’à tous les autres, les poils s’hérissent, les rictus se forment. La méritocratie est un mensonge dit-on. Elle est impossible entend-on ailleurs. Le mérite n’est ni définissable ni reconnaissable lance t-on encore. L’utopie égalitaire, bien plus mensongère et impossible a eu ça d’incroyable qu’elle a interdit la Méritocratie. Car si l’égalité est une belle valeur, érigée en dogme elle devient mortifère. Elle interdit la différence et la liberté. La Méritocratie ne se base pas sur le nom commun “le mérite”, trop facilement manipulable, mais sur le verbe “mériter”. La nuance peut sembler faible, mais elle est capitale. Mériter un traitement veut simplement dire que notre personne a le droit de subir ce traitement, qu’il soit positif ou négatif. On ne mesure pas ce droit à la quantité de travail fournit ou à la bonne volonté, mais uniquement à l’accord entre le traitement assuré et les compétences attendues peu importe leur origine. Pour un monde juste il faudrait certes réduire l’influence des compétences issues du milieu social. Mais il ne faut jamais les nier, encore moins celles biologiques. L’utopie égalitaire a postulé que nous étions tous égaux. Cela est faux. Si nous sommes tous différents, et nous le sommes, cela s’accompagne forcément d’une hiérarchisation entre les individus en fonction du domaine. Cette hiérarchisation peut tout à fait s’inverser en examinant depuis un autre angle. Pour garantir la Méritocratie il faut ainsi dresser un cadre où les meilleurs dans un domaine auront le plus d’opportunités dans ce domaine, peu importe leurs fréquentations ou leur identité. Ainsi, chacun trouvera le domaine qui s’accorde le mieux entre l’importance qu’ils donnent à leur préférence et à leurs compétences. La Méritocratie garantit une société juste, libre et efficace contrairement à l’utopie égalitaire qui ne garantit que discrimination positive, nivellement vers le bas et improductivité.

        L’objectif du manifeste est de dresser un portrait des politiques à mettre en place impérativement pour rétablir des structures saines en France. Bien que nous ayons forcément des biais, nous avons rédigé ce texte avec le plus grand pragmatisme qui nous était possible. Nous voulons que cet écrit soit lisible par tous, ainsi nous resterons concis dans chacune de nos parties qui s'articulent ainsi: a) Champs abordés, b) Problématiques contemporaines, c) Solutions. Je vous souhaite une excellente lecture, et puisse votre regard s'aiguiser grâce à notre travail.
        <br><br><br>
    </div>
    <div class="manif-chapters"id="Sécurité">
        <h1 class="center" >Sécurité et Immigration</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">
        La sécurité est la première des libertés, non pas parce qu’il faut la privilégier par rapport aux autres, mais parce qu’elle permet l’existence de ces dernières. En effet la liberté nécessite que l’on ait le droit de faire une action, mais aussi que l’on soit assuré que personne ne nous oblige à la faire. Etes vous libre de vous exprimer si une milice bien organisée ne peut empêcher votre adversaire politique de vous censurer par sa force ? La sécurité est la première des libertés parce qu’elle fonde l'État, en nous sortant de la guerre de tous contre tous en définissant le « nous » : la nation. Garantir la tranquillité à l’intérieur de la cité nécessite que les portes de celles-ci soient contrôlées par les citoyens, et que ceux-ci, en cas de faillite de l’état à sa mission, puissent par une volonté de vivre-ensemble continuer à perpétuer la communauté par autre chose qu’un contrat : par l’identité.
        "Essayez d'intégrer de l'huile et du vinaigre. Agitez la bouteille. Au bout d'un moment, ils se sépareront de nouveau. Les Arabes sont des Arabes, les Français sont des Français. Vous croyez que le corps français peut absorber dix millions de musulmans, qui demain seront vingt millions et après-demain quarante ? Si nous faisons l'intégration, si tous les Arabes et Berbères d'Algérie étaient considérés comme Français, comment les empêcherait-on de venir s'installer en métropole, alors que le niveau de vie y est tellement plus élevé ? Mon village ne s'appellerait plus Colombey-les-Deux-Eglises, mais Colombey-les-Deux-Mosquées !" - - Charles De Gaulle
        Depuis les années 70, les différents gouvernements, de « droite » de gauche, tous incompétents, ont sciemment appliqué une politique d’immigration massive, nous tâcherons de le démontrer. A partir de cette date, on a cru bon de faire venir non plus des individus mais une communauté : la famille. Attitude généreuse peut-être, mais la nation n’a à être généreuse qu’avec ses enfants. Avec le regroupement familial un immigré en amène 3 autres, puis 9 autres et ainsi de suite, tout immigré devient malgré lui une porte d’entrée à notre territoire. Les chiffres de l’immigration sont criants : depuis 2006, le nombre de titres de séjour a toujours tourné autour de 200 000 par an, plus d’hommes que la Grande Armée traversant le Rhin. Ce chiffre s’accélère depuis plusieurs années, l’année 2019 fut la pire avec 285 000 titres, malgré le supposé fascisme de notre président, contre 200 000 en 2010, vous noterez que ces deux dates correspondent à des gouvernements réputés de « droite » ; que nos amis conservateurs réfléchissent. Avec la moyenne établie on arrive à plus de 2 600 000 immigrés. Et ce n’est que la surface de l’iceberg, ne sont pas comptés les 177 000 demandes d’asile rien que cette année (en hausse de 9%), les mineurs isolés, et les clandestins dont il est impossible d’établir un chiffre précis. Les décodeurs affirment pourtant que la proportion d’immigrés est stable en France, ce qui est faux : nous sommes passés de 6,6% en 1968 à 9,3% en 2015 selon l’INSEE sans compter que la proportion de personnes extra-européennes sont passés de 23,6% à plus de 60%, une proportion qui n’est pas près de s’inverser au vu de la démographie des deux continents.
        La proportion semble rester faible, il faut prendre en compte que la proportion d’immigrés ici présentée, ne correspond qu’au nombre des personnes disposant d’une nationalité étrangère. Cette proportion ne risque pas de bouger, puisque les fils et filles d’immigrés bénéficient d’un droit du sol qui considère qu’un porc né dans une écurie devient un cheval ! La nationalité n’est pas un bon facteur pour analyser la situation, la communauté nationale n’étant pas définie par un bout de papier mais par une communauté de destin. En 2008, songez que les 5,3 millions d’immigrés (dont 2/3 extra-européen) ont pondu 6,7 millions de descendants, et ce alors que notre natalité peine à assurer ne serait-ce que notre renouvellement, ils sont eux en constante expansion. Sans compter la centaine de millier de naturalisation chaque année, à plus de 60% destiné aux africains
        Mais enfin ils sont français eux aussi, ils ont des papiers ! Est-ce que cela suffit ? Aristote nous disait déjà que non. Une nation ce n’est pas qu’une masse d’individu, c’est un peuple qui se sent uni, qui est transcendé par quelque chose. Comment savoir si certains de nos compatriotes se battront pour nous si par malheur nous devions par les hasards du destin renouveler les efforts de nos ancêtres les poilus, lorsque leur loyauté est déjà démentie par l’équipe de foot qu’ils soutiennent ? Une situation que l’auteur de ces lignes connaît personnellement. La nation est une âme disait Renan, une âme ne se distribue pas comme un prospectus, elle imprègne totalement l’individu, ne fait qu’un avec lui et lui impose une attitude. Je doute que les djihadistes qui ont brûlé leur passeport et les supporters des fennecs qui sifflent la marseillaise soient français malgré une carte d’identité affirmant l’inverse, de leur propre avis. Pour bien partir, ne confondons pas identité nationale et carte d’identité nationale.
        Le multiculturalisme que certains avancent pour décourager toute tentative d’assimilation, est en lui-même destructeur de culture. Celui-ci ordonne aux français d’abandonner leur creuset, leur tradition d’assimilation, tout cela au profit d’un communautarisme anglo-saxon qui n’a pour effet que de déclencher des émeutes ethniques régulières. N’avons-nous pas assez de grands auteurs ou cinéastes à diffuser à une jeunesse américanisée et quasiment analphabète, avant de leur apprendre la culture turque ou polonaise ? Mais soit, admettons que tous les enfants de France parviennent à bien connaître notre propre culture (sûrement pas grâce à ceux qui veulent accueillir les immigrés), j’admets que la découverte de nouvelles cultures peut être intéressante. Mais chaque immigré ne vient pas pour faire une exposition sur son pays d’origine, la diversité culturelle n’implique pas une grande quantité d’immigré mais une grande qualité. Qu’a apportée l’immigration massive depuis 40 ans en termes de plus-value culturelle ? Un dégoût par nos compatriotes d’une culture étrangère que la quantité a folklorisé, que notre abandon de l’assimilation a américanisé, et à laquelle le multiculturalisme a donné une forme violente.
        Car n’oublions pas que cette partie concerne également la sécurité, cette thématique et l’immigration étant étroitement liées. Une société multiculturelle est forcément multiconflictuelle. Les guerres de religions, le génocide du Rwanda et les émeutes raciales aux Etats-Unis nous l’ont douloureusement appris. Lorsque plus rien d’autre qu’un passeport ne relie les citoyens d’un pays, alors c’est qu’ils ne font plus tous partie de ce pays. La peur de l’autre, du bouleversement de nos habitudes est une peur naturelle de l’homme, qui le pousse à se battre pour préserver son mode de vie. Nos ancêtres ne seraient-ils morts que pour respecter un contrat social ? On observe une communautarisation du territoire de plus en plus grande, avec des quartiers qui ne sont plus que des enclaves étrangères et ce sur notre sol. Ceux-ci, sobrement nommés « quartiers de reconquête républicaine » sont au nombre de 751. Le caractère culturel de la délinquance a été avancé dans plusieurs études comme celle du sociologue Hugues Lagrange datée de 2010, où il admettait qu’à statut social équivalent les adolescents élevés dans des familles originaires du Sahel ont 3 à 4 fois plus de chances que ceux élevés dans les familles autochtones de commettre un délit. Dommage qu’il en tire la conclusion de détruire un peu plus notre modèle d’assimilation, à l’image d’un européiste qui se plaint que l’Europe ne marche pas car on ne lui cède jamais assez de souveraineté.
        On constate un criant rapport entre immigration et délinquance, criminalité et terrorisme. Aujourd’hui 23,5% de notre population carcérale a une nationalité étrangère, et Sarkozy, fasciste bien connu, a empêché que l’on puisse les expulser. Voici quelques chiffres du ministère de l’intérieur pour le statut des personnes mises en cause lors de l’année 2018, où la proportion d’étrangers était de 7,1% selon l’INSEE :
        - 16% pour les homicides
        - 15% pour les coups et blessures volontaires
        - 14% pour les violences sexuelles
        - 17% pour les vols commis avec armes
        - 32% des vols violents sans armes
        - 27% des vols commis sans violence
        - 27% pour les cambriolages
        - 14% pour « escroqueries et infractions assimilés »
        - 26% pour les vols d’accessoires et dans les véhicules
        Dans un monde cruellement matérialiste, où l’argent est l’unité de valeur unique, ce coût sécuritaire, démographique et culturel doit être compensé par des bienfaits économiques. L’immigration ferait comme par miracle le consensus entre libéraux et keynésiens : l’immigration augmente la population active et donc le PIB, donc la croissance. Les premiers accordent à l’étranger le droit d’aller et de venir par haine de l'État (et donc de frontières) et du bien commun, le second par la relance économique par l’importation massive de nouveaux consommateurs. Mais la croissance économique n’est pas le seul objectif d’une économie, si la croissance augmente de 1% mais que cette hausse se fait par une augmentation de 2%, alors le PIB par habitant baissera. L’immigration est utile pour cacher la désindustrialisation et la non création de richesse par nos dirigeants : on importe 200 000 bouches à nourrir et hop ! La croissance est positive ! votez pour moi ! Sauf que cette croissance n’est pas plus gratuite que l’accueil des étrangers. Nous nous garderons d’évoquer le coût financier définitif de l’immigration, sujet à débat, mais il est évalué au bas mot à 6,57 milliards par la Cour des comptes, et une étude du CEPII publié en 2018 évalue ce coût sur 30 ans à 1,64 points de PIB, à noter que ce calcul s’arrête en 2011, avant la crise migratoire. Non, la France ne peut non seulement plus accueillir des immigrés supplémentaires, mais doit se délester d’une partie de ceux qu’elle a déjà. A l’heure du déficit budgétaire, et du chômage de masse accueillir une population peu qualifiée et moins propice à occuper un emploi (14% contre 8%) ne peut qu’aggraver la situation économique. Sans compter que l’immigration fait baisser les salaires : lorsque l’offre de travail augmente alors son prix baisse mécaniquement lorsque la demande ne suit pas.
        Ce constat sans appel, convaincra toute personne douée de raison et de bonne foi que l’immigration de masse n’est plus possible. En voyant la réalité, le plus cosmopolite des hommes aurait l’idée de bâtir un mur. ET pourtant : OUI, l’assimilation est possible, elle a existé et elle existera encore, n’en déplaise aux racistes. Ce processus s’effectue par amour du pays d’accueil d’une part, et certaines contraintes d’autre part. Seul un petit nombre d’individus remplissent ces deux conditions. Prenons un exemple : si un étranger aimant arrive dans une ville, s’il veut se rapprocher socialement des autochtones il devra se rapprocher culturellement d’eux, l’être humain est ainsi fait qu’il lui sera plus facile de communiquer avec une personne semblable à lui. En revanche, si les immigrés sont suffisamment nombreux, alors plus besoin d’adopter les coutumes locales, puisque ceux qui viennent du pays d’envoi vous permettront d’obtenir les relations sociales si nécessaires à notre espèce. Ainsi les ghettos se sont formés. On assimile des individus, pas des peuples. L’assimilation nécessite de faire sienne l’histoire de France, et donc d’abandonner ses racines personnelles, pour les planter de nouveau. Assimilation et remigration ne s’opposent pas mais se complètent.
        Entendons-nous bien, il ne s’agit aucunement de discriminer une partie de nos concitoyens sur leur couleur de peau. Tout politique se fera sur des critères strictement comportementaux et individuels, dans le respect de la dignité humaine et de l'État de droit. L’historien de gauche Pierre Milza a démontré que 2/3 des immigrés italiens venus en France sont repartis, il n’est pas raciste de traiter les immigrés d’aujourd’hui avec la même rigueur que les immigrés d’hier. Tout racisme est l’ennemi de la France, et c’est par une politique migratoire ferme mais juste que nous éviterons de plus grandes tensions.

        Il est maintenant temps de s’attaquer au problème de la sécurité publique.
        On constate que contrairement à un mantra progressiste qui répète inlassablement que c’était pire avant, le taux de criminalité a fortement augmenté depuis les Trente Glorieuses. D’après la Direction centrale de la Police Judiciaire, le taux de criminalité est passé de 14,06 0/00 en 1949, à 62,35 0/00 en 2005.

        Et si on semble se réjouir d’une baisse de la criminalité depuis 2001, celle-ci repart à la hausse depuis 2010 avec une augmentation en 2019 des homicides (+4%), des violences sexuelles (+12%), et des violences volontaires (+8%). On observe cependant une baisse de 9% des vols violents la même année. Le nombre de tentatives d’homicide à quant à lui doublé depuis 20 ans. 120 attaques au couteau sont perpétrées chaque jour.
        L’INSEE nous montre des chiffres pour l’année 2018 effrayants : 1,1 million d’actes de vandalisme sur voiture, 812 000 majeurs victimes de violences physiques ou sexuelles hors ménage, 3,8 millions de déclarations d’atteinte aux biens visant un véhicule ou une résidence, 186 000 atteintes volontaires à l’intégrité physique.
        IL est complètement anormal que la Pologne, la Corée du sud et l’Italie présentent un taux d’homicides 2 fois inférieur au nôtre.
        Abordons désormais les solutions :
        - LA priorité absolue est la réforme du code de la nationalité : supprimer le droit du sol, la naturalisation ne s’obtiendra plus qu’après avoir rendu un service à la nation et si le naturalisé a les codes culturels. Prévoir une peine de déchéance de nationalité ou d’ostracisme pour certains crimes (trahison, terrorisme…). Élargir l’article 23-7 du code civil à l’ensemble des français, et préciser que des comportements culturels inadaptés seront considérés comme des comportements étrangers et donc susceptibles de conduire à une déchéance de nationalité.
        - Seront expulsés systématiquement : les clandestins, les délinquants, les potentiels terroristes, les chômeurs de moyenne durée (1 an sauf justificatif). Etablissement d’un crime de trafic d’êtres humains qui comprendra l’aide à l’entrée sur le territoire ou à son séjour envers des clandestins
        - Priorité nationale dans l’attribution des emplois et des allocations de toute sorte
        - Nous ne stopperons pas l’immigration, mais nous la ciblerons, par le retour de contrôles aux frontières. Établir un classement des immigrés selon leurs compétences, de pas à très qualifié. Chaque année le gouvernement établira avec les partenaires sociaux des quotas de titres de travail selon le secteur et la qualification. Suppression du regroupement familial.
        - La demande d’asile devra se faire dans une ambassade française à l’étranger. Seront considérés éligible ceux qui ont reçu des menaces politiques directes dans leur pays. Financer des camps d’accueil dans les pays limitrophes des zones de départ.
        - Les immigrés n’auront droit aux mêmes allocations qu’après un an de cotisation à l’exception des allocations familiales qui resteront accordées aux français.
        - Port d’arme citoyen : des individus volontaires pourront obtenir le droit de porter une arme à feu discrètement s’ils sont majeurs, français, ont un entraînement aux armes à feu, avoir effectué un service militaire ou s’être engagé dans la réserve, ne pas avoir d’antécédents judiciaires ou psychiatriques même léger. Des tests seront régulièrement effectués pour renouveler la licence, tous les 2 ans. L’achat et le port d’armes non létales, tels que les bombes au poivre ou les armes contondantes sera facilité.
        - Mieux entraîner les forces de l’ordre au maniement des armes et augmenter leurs effectifs. La notion de légitime défense pour les policiers sera étendue. Une riposte physique mais non létale sera autorisée en cas d’outrage à agent ou de refus d’obtempérer. Le droit d’utiliser son arme à feu en cas d’interpellation ou de menaces envers leur personne sera autorisé de façon non proportionnelle à la menace. Les coups contre tout homme à terre sera sanctionné.
        - Fonder un corps de réserve de la police qui aura pour tâche d’épauler la police dans ses missions mineures et les moins exposées au risque. Ce corps sera constitué de volontaires majeurs, entraînés et encadrés systématiquement par des professionnels.
        - Repenser le rôle de la garde nationale dans notre politique de sécurité publique. Elle aura désormais un rôle de patrouille et d’interpellation.
        - Règle d’usage d’une arme : 3 sommations sur personne représentant une menace physique directe pour soi ou pour autrui ou commettant un délit de fuite. La proportionnalité de la menace n’est pas nécessaire. De plus le tir sera possible sur les individus ne s’étant pas mis en position couché s’ils sont dans une propriété privée.

        Ces mesures non exhaustives ne peuvent s’appliquer que dans le cadre d’une sortie de l’UE, ainsi que d’une réforme profonde de la justice
        <br><br><br>
    </div>
    <div class="manif-chapters"id="Education">
        <h1 class="center" >Education</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">
        Une mauvaise éducation généralisée c’est assurer une génération malade et dangereuse pour notre avenir. Ici seront abordées les politiques à mettre en œuvre pour améliorer le système éducatif en perdition. Les cycles primaires et secondaires ainsi que l’enseignement supérieur seront traités.
        Dressons tout d’abord un tableau complet de la situation de l’éducation en France. Force est de constater que celle-ci est en mauvaise posture. La France, symbole de l'excellence, chute chaque année un peu plus dans le classement mondial que ce soit en langues ou en mathématiques. En cause ici: l’idéologie égalitaire. L’autorité a également disparu des écoles, (mettre chiffre du dossier données éducations/ formations professorales). Les Universités sont gangrenées en immense majorité par des associations de l’extrême gauche rendant les conditions d’études déplorables. Pourtant l’éducation, le supérieur et la recherche sont ici pris en compte, représente la première dépense de l'État.
        <br><br><br>
    </div>
    <div class="manif-chapters"id="Ecologie" >
        <h1 class="center" >Ecologie</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">
        Une pénurie de ressources et un excès de pollution se paie par une diminution drastique de la qualité de vie pour toute la population sur tous les plans. Tous les sujets liés à l’écologie sont développés dans cette partie. Vous y trouverez ici des mesures concernant Le transport, l’électricité, les déchets, le bâtiment, l’alimentation et la mondialisation.
        <br><br><br>
    </div>
    <div class="manif-chapters" id="Relations">
        <h1 class="center" >Relations Internationales</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">

        La France dans le monde

        En Europe de l’est/centre/nord
        Sur le pourtour méditérannéen
        L’Union Latine
        L’influence au Maghreb + cas de la Lybie
        Turquie + Moyen-Orient
        En Amérique du Nord
        Renaissance du français en Amérique, politique culturelle et renaissance de la langue française
        En Amérique du Sud
        Liaisons avec l’ALBA, politique d’influence de l’Amérique latine dans le cadre de l’Union Latine (échanges internationaux, etc.)
        En Afrique de l’Ouest
        Plans d’investissements massif, liaisons universitaires, promotion du français, apaisement des relations, favoriser une intégration plus poussé dans la CEDEAO
        En Afrique de l’Est
        Aide à l’éthiopie dans le cadre de sa guerre avec la somalie et l’érythrée

        En Afrique du Sud
        En Asie Pacifique
        Renforcer nos liens avec l’Australie et la Nouvelle-Zélande
        - En Asie du Sud
        - Aide de l’Inde dans son conflit avec le Pakistan, politique de rapprochement scolaire et promotion de l’influence française des les indes.
        - Asie

        <br><br><br>
    </div>
    <div class="manif-chapters"id="Défense">
        <h1 class="center" >Défense</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">
        <br><br><br>
    </div>
    <div class="manif-chapters"id="Finance">
        <h1 class="center" >Finance</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">
        La Finance a considérablement muté depuis la révolution des NTIC. La crise du covid n’a fait que souligner la déconnexion avec la sphère réelle. Le marché se concentre de plus en plus et le risque systémique ne fait que s'accroître. Les Banques Centrales arrosent à la moindre inflexion les MF de liquidité pour y pallier. La finance actuelle profite aux agents qui utilisent ces nouvelles possibilités de placements et laisse des centaines de millions d'individus vivre qu’avec les ressources de leurs travail. Mon approche se basera donc sur plusieurs aspects:
        -Rétablir une finance au service de l'économie réelle.
        -Informer et éduquer davantage sur le fonctionnement de l’économie et de la finance.
        - Proposer des mesures pour atténuer ce risque systémique.
        <br><br><br>
    </div>
    <div class="manif-chapters"id="Agriculture">
        <h1 class="center" >Agriculture</h1>
        <img src="img/soulignement.png" alt="" class="soulignement">
        Dans cette partie, je vais développer les problématiques liées à l’agriculture. La France est un pays historiquement agricole et aujourd’hui, nous devons faire en sorte d’avoir la meilleure agriculture possible afin de préserver la santé de nos concitoyens et nos intérêts économiques. Notre agriculture qui promeut la quantité au détriment de la qualité doit devenir une agriculture responsable et de qualité même si nous devons perdre en quantité pour cela. Il en va de la survie de nos agriculteurs et de notre souveraineté alimentaire. Si les agriculteurs sont payés une misère par l’industrie agroalimentaire, qu’est-ce qui, dans quelques années, les empêchera de délocaliser par la suite dans des pays du tiers-monde, où personne n’ira regarder quels sont les produits chimiques qui sont répandus dans les champs ? Nous sommes de même en capacité de produire suffisamment de ressources pour nourrir notre population. L’importation de denrées étrangères ne devrait être que limitée afin de permettre à nos agriculteurs français de travailler et vivre correctement.

        Constat actuel :

        L'alimentation du bétail est délétère pour l'environnement, la santé du bétail et des consommateurs. Le couple maïs/soja trop souvent utilisé amène par exemple un très fort dérèglement de l'équilibre oméga 6 et 3. Cela appauvrit aussi énormément les sols car défavorise la polyculture et donc par extension la rotation des productions sur un terrain.

        Les politiques d'aides à l'irrigation intensive posent des problèmes, notamment de sécheresse. Le plus concerné est la production du maïs, utilisé en couple avec le soja dans la majorité de l'alimentation du bétail. Les agriculteurs touchent des subventions de la part de l’Union Européenne afin de faire des travaux pour irriguer leurs champs. “L'irrigation agricole utilise près de 5 milliards de m3 d'eau (60% de la consommation finale totale).”, “Les prix agricoles soutenus ont également conduit à un recours accru à l'irrigation et à la mise en valeur de terres qui sans cela seraient restées des sanctuaires : le drainage des marais pour y faire pousser du maïs subventionné a, en France, contribué à la destruction de zones humides et à la perte d'habitat de nombreuses espèces.” d’après Jean-Christophe Bureau. Il serait temps de promouvoir des cultures plus responsables et adaptées à notre climat.

        L'installation d'une nouvelle exploitation n’est pas vraiment facilitée car cela demande de gros investissements. Rappelons que l’aide maximale en zone de plaine provenant de la Dotation Jeune Agriculteur est de 15 000€. Cela représente plus ou moins le prix d’un tracteur bas de gamme. La difficulté de s’installer se ressent fortement quand on regarde l’âge des agriculteurs. En 2019, 55% des agriculteurs ont plus de 50 ans et seulement 1% moins de 25 (source INSEE 2020), l’âge moyen des agriculteurs en 2016 est de 52 ans. La Mutualité Sociale Agricole a annoncé lors d’une conférence de presse le 19 juin 2019 qu’en 10 ans, la moitié des agriculteurs seront à la retraite. Toujours d’après la MSA, on compte une nouvelle installation pour deux ou trois départs à la retraite. On dénombrait 2,3 millions d’exploitations agricoles en 1955 contre un peu moins de 490 000 en 2010 (source INRAE 2020). Cette baisse du nombre d’exploitations se traduit par une baisse drastique de la part de la population agricole dans la population active, passant de 7,3% en 1984 à 1,3% en 2019 (INSEE 2020). Il est impératif d’apporter du sang neuf dans cette profession. Ces nouveaux agriculteurs doivent être formés à une agriculture responsable : respectueuse de l’environnement, des animaux, des plantes, des consommateurs et des agriculteurs. De même, ce n’est pas un numéro vert qui sauvera le plus d’agriculteurs du suicide. Ce numéro vert est important, certes. Il permet d’éviter de nombreux suicides, il est vrai. Mais ce n’est pas un pansement qui soignera une plaie béante. Il faut remonter à la source du problème : la très, trop, faible rémunération des agriculteurs et les conditions de travail souvent très difficiles et qui ne sont pas reconnues à leur juste valeur. Faire face à la concurrence déloyale n’arrange pas. Les nombreux accords de libre-échange signés par l’Union Européenne font que nous avons sur le marché beaucoup de denrées alimentaires à très bas prix qui raflent les plus grosses parts du marché.

        La rémunération des agriculteurs est dans la plupart des cas très dérisoire par rapport à la production. On parle d’environ 20% d’agriculteurs qui n’ont pas eu de revenus en 2017 et d’un salaire moyen à hauteur de 1390 euros net mensuels avec donc de très grandes disparités. La faute à un développement du productivisme dans la période d’après-guerre au détriment de la qualité des productions. Nous avons favorisé des espèces à meilleur rendement mais plus faible résistance et généralement moins bon goût. Nous avons couplé cela avec une utilisation massive d’engrais chimiques, pesticides etc qui ne profitent à personne à part les industries qui fabriquent ces produits. La réglementation actuelle permet de nombreux pesticides, engrais, et autres produits chimiques délétères pour la santé des consommateurs mais aussi des producteurs et autres intermédiaires. On recense de nombreux cancers et autres maladies graves dues à ces produits, cela concerne aussi les produits utilisés pour la conservation des denrées. De plus, les entreprises agroalimentaires sont très peu respectueuses de la santé et du travail des agriculteurs. Il est d’ailleurs ardu pour les agriculteurs et professionnels de l’agroalimentaire de faire reconnaître ces conséquences sur leur santé comme maladie professionnelle. Les conditions de travail déplorables des agriculteurs ne s’arrêtent pas là. Travail le week-end, de nuit, peu de vacances. En 2019, la moyenne d’heures de travail déclarée est de 55h hebdomadaire contre 37h de moyenne pour l’ensemble des emplois. Cela se traduit par une différence de 65% d’écart de durée de travail annuelle entre les agriculteurs et l’ensemble des personnes en emploi.


        Les méthaniseurs et autres moyens de conversion des déchets nocifs en production comme du bioéthanol par exemple doivent être extrêmement encadrés et peu rentables. En effet, leur utilisation incite la production de ces déchets afin de maximiser les profits, au détriment de la pollution, notamment des eaux et des sols.

        Solutions :

        Afin d’améliorer la qualité de notre agriculture, il est primordial de mener une politique de forte répression des engrais et produits chimiques. La quantité produite est trop élevée. Nous devons promouvoir bien plus la polyculture et la rotation des cultures pour préserver les sols et les nappes phréatiques. Lutter contre la polyculture, encourager les exploitations agricoles autosuffisantes en instaurant des taxes. Si nous ne pouvons pas instaurer de droits de douane à cause de l’Union Européenne et de ses accords de libre-échange, nous pouvons instaurer une taxe pour nos agriculteurs qui nourrissent leur bétail principalement avec de la nourriture étrangère et une prime pour ceux qui produisent eux-mêmes leurs ressources. De plus, il serait bienvenu de taxer les exploitants qui nourrissent à hauteur de 40% ou plus leur bétail de maïs et de soja. Nous l’avons vu précédemment, ce régime n’est bénéfique ni pour la planète ni pour notre consommation. Dans la même logique, nous devons cesser de subventionner l’irrigation intensive pour promouvoir des cultures qui ne le nécessitent pas et viendraient remplacer le maïs. Il serait aussi demandé aux grandes surfaces de séparer clairement les produits issus d’agriculture responsable des autres afin d’encourager leur consommation. Une agriculture responsable serait définie globalement par : un respect du bien-être animal, une culture respectant une charte précise de produits chimiques acceptés, un élevage garanti sans (ou avec extrêmement peu) d’antibiotiques et nourris avec des denrées respectant la charte précédente à hauteur d’au moins 80% d’origine France et une limite de 10% maximum de soja d’importation dans la nourriture des animaux. Tout ceci serait bien entendu contrôlé.

        Toujours pour promouvoir une agriculture de qualité, il faut revoir la liste des produits chimiques interdits et durcir grandement les exigences. Par contre, accompagner les agriculteurs dans cette transition est primordial. Cela passe par des subventions afin de permettre d’acheter du matériel compensant ces produits par exemple, dans le cas du blé au lieu d’utiliser des produits pour permettre sa conservation dans un silo normal, donner des subventions pour l’achat de silo réfrigéré, plus cher qu’un silo normal mais qui évite d’utiliser des produits hautement toxiques. Ce changement est essentiel pour la qualité de la nourriture qui sera consommée par les Français, pour protéger la biodiversité mais aussi pour protéger la santé de nos agriculteurs.

        Pour encourager l’installation des nouveaux agriculteurs, il est fondamental de donner une meilleure image du métier et d’améliorer les conditions de travail ainsi que la rémunération comme dit précédemment. Cela devient de plus en plus urgent à cause du vieillissement de la population et le non-renouvellement des actifs. De plus, il nous paraît crucial d’aider économiquement les nouveaux exploitants à cause du coût du matériel nécessaire, des terres etc. Pour cette raison, l’Etat consentirait à un prêt important aux nouveaux exploitants. Les exploitants n’auraient pas à rembourser entièrement le prêt directement mais vendraient au prix minimal une partie importante de leur production à l’Etat qui pourrait ainsi revendre ceci et le prêt serait remboursé grâce à la marge effectuée par l’Etat.

    </div>
    <br><br><br>
</div>
<div class="manif-chapters"id="Conclusion">
    <h1 class="center" >Conclusion</h1>
    <img src="img/soulignement.png" alt="" class="soulignement">
    <br><br><br>
</div>